### ISSUE TITLE
Corregir Settings

### ISSUE THREAD

**Issue by mgutierrezc** [verduralegorica/meds_primero#2]
El nombre que va en su app_sequence siempre debe ser el mismo que el nombre del repo

**Comment by verduralegorica** [comment]
Listo!

**Comment by mgutierrezc** [comment]
1. El nombre de la sesion de tratamiento nunca debe tener el mismo que el de la sesion de control
1. El nombre de la sesion nunca debe ir en mayusculas, sin caracteres especiales y sin espacios. Usar minusculas y guiones bajos `_`
1. El nombre de la sesion en `name` nunca debe ser generico. Denle un nombre de 1 o 2 palabras maximo que identifique la sesión
1. Deben añadir una entrada más en su diccionario de SESSION_CONFIGS llamada `display_name`. Ese es el nombre que veran en pantalla a la hora de escoger su experimento. No debe ser generico, debe ser relacionado con su experimento y debe tener máximo 3 palabras

**Comment by mgutierrezc** [comment]
> El nombre que va en su app_sequence siempre debe ser el mismo que el nombre del repo

Cuando les dí este comentario, no esperaba que cambiaran el nombre de sus repos, sino el valor de `app_sequence`.

Los nombres que sus repos tenian antes estaban bien. No le den **nombres genéricos** como "primero", "repositorio", "etc" a sus repositorios ni a cualquier otro elemento que identifique su experimento. 

Coloquen de vuelta el prefijo `Meds_`. Es necesario realizar esta correccion en **todos los repos** de su experimento, pues sino se desordenaría el servidor

- Además, deben cambiar el nombre de la aplicación `no_mobile` a `MobilePhones`

Actualicen su app_sequence para ese cambio en todos los Readme segun corresponda
