### ISSUE TITLE
Corregir información adicional exp en línea

### ISSUE THREAD

**Issue by mgutierrezc** [verduralegorica/meds_primero#6]
Sobre la sgte sección:

https://github.com/verduralegorica/meds_primero/blob/3bdeebfdece7d6c3e03f542086af72238f547498/templates/meds_primero/Instrucciones.html#L27-L32

- Los participantes no deben llamar nunca al laboratorio, solo mandar mensajes de WhatsApp. Asimismo, tambien debe aparecer siempre el correo del laboratorio para que nos contacten por correo

- La información que les estan mostrando en la parte citada ya se les da a los participantes por correo 3 veces de acuerdo al protocolo (al inscribirse, 30 min antes y en el correo de inicio de sesion), así que no es necesario volverla a colocar aquí. Por favor, en su lugar, coloquen el template de contacto que aparece en las demás páginas abajo del botón `Siguiente`

Sobre esta otra:
https://github.com/verduralegorica/meds_primero/blob/3bdeebfdece7d6c3e03f542086af72238f547498/templates/meds_primero/Instrucciones.html#L33-L42

- Ya les damos esa información al momento de invitarlos al experimento y en la última página, por lo tanto, no colocarla otra vez en esta sección

- Todavía no me han indicado qué medios de pago van a usar en su experimento. Por favor, comentarlos en este issue

**Comment by verduralegorica** [comment]
Corregido!
Respecto a los pagos, se usará yape/lukita/tunki o CCI.

**Comment by mgutierrezc** [comment]
Si no hay nada pendiente a resolver de este issue, cierrenlo por favor. En caso contrario, cerrarlo al terminar
