### ISSUE TITLE
Timer: Pregunta

### ISSUE THREAD

**Issue by mgutierrezc** [verduralegorica/meds_primero#7]
Su asesor les ha autorizado/sugerido usar un timer para esta sección de su experimento?

![exp_meds timer](https://user-images.githubusercontent.com/43623521/92450743-6a04dc00-f181-11ea-99f1-2516011955d9.png)

Estos no tienen tan buena fama, pues no les asegura que sus participantes hayan entendido el experimento al forzarlos a tener solo ese tiempo para hacerlo.

En el lab, les hablamos directamente a los participantes que se toman mucho tiempo en las preguntas o en alguna seccion si es que esa es su preocupación

En caso no haya sido aprobado por su asesor, les pediría no incluirlo. En caso contrario, no hay problema

**Comment by verduralegorica** [comment]
Buen punto, entonces no va!
